### ISSUE TITLE
Seg fault 

### ISSUE THREAD

**Issue by rahul342** [ksss/freetype#1]
Hi @ksss 

We are running into seg fault with the library

```
c:0100 p:---- s:0563 e:000562 CFUNC  :FT_Outline_Decompose
c:0099 p:0094 s:0556 E:002158 METHOD /home/circleci/repo/vendor/bundle/ruby/2.6.0/gems/freetype-0.0.6/lib/freetype/api.rb:227
```

I noticed that in the current master, you have a commit https://github.com/ksss/freetype/commit/8e48fb665fbfe7055741e8ea8a33fa80862f9f83#diff-9355532c9584dba8cb32ffb9c12a4a17b420f84439330059ef12c08ab49e228e that seems probably you added for same exact error. Is that correct?

Could you please release a new version of the gem? We are using yours text2svg gem which require freetype.

Please let me know if this error is not related to that change. Thank you!

**Comment by rahul342** [comment]
Sorry seems like false information.

**Comment by ksss** [comment]
Thank you for using this library.
Please let me know if you need anything else.
